//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestePratico.Web.WCF.UFAppService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF.UFAppService.IAppServiceBaseOf_UF")]
    public interface IAppServiceBaseOf_UF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppServiceBaseOf_UF/GetById", ReplyAction="http://tempuri.org/IAppServiceBaseOf_UF/GetByIdResponse")]
        TestePratico.Domain.Entities.UF GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppServiceBaseOf_UF/GetById", ReplyAction="http://tempuri.org/IAppServiceBaseOf_UF/GetByIdResponse")]
        System.Threading.Tasks.Task<TestePratico.Domain.Entities.UF> GetByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppServiceBaseOf_UF/GetAll", ReplyAction="http://tempuri.org/IAppServiceBaseOf_UF/GetAllResponse")]
        TestePratico.Domain.Entities.UF[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppServiceBaseOf_UF/GetAll", ReplyAction="http://tempuri.org/IAppServiceBaseOf_UF/GetAllResponse")]
        System.Threading.Tasks.Task<TestePratico.Domain.Entities.UF[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppServiceBaseOf_UF/Add", ReplyAction="http://tempuri.org/IAppServiceBaseOf_UF/AddResponse")]
        TestePratico.Domain.Validation.ValidationResult Add(TestePratico.Domain.Entities.UF entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppServiceBaseOf_UF/Add", ReplyAction="http://tempuri.org/IAppServiceBaseOf_UF/AddResponse")]
        System.Threading.Tasks.Task<TestePratico.Domain.Validation.ValidationResult> AddAsync(TestePratico.Domain.Entities.UF entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppServiceBaseOf_UF/Update", ReplyAction="http://tempuri.org/IAppServiceBaseOf_UF/UpdateResponse")]
        TestePratico.Domain.Validation.ValidationResult Update(TestePratico.Domain.Entities.UF entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppServiceBaseOf_UF/Update", ReplyAction="http://tempuri.org/IAppServiceBaseOf_UF/UpdateResponse")]
        System.Threading.Tasks.Task<TestePratico.Domain.Validation.ValidationResult> UpdateAsync(TestePratico.Domain.Entities.UF entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppServiceBaseOf_UF/Remove", ReplyAction="http://tempuri.org/IAppServiceBaseOf_UF/RemoveResponse")]
        TestePratico.Domain.Validation.ValidationResult Remove(TestePratico.Domain.Entities.UF entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppServiceBaseOf_UF/Remove", ReplyAction="http://tempuri.org/IAppServiceBaseOf_UF/RemoveResponse")]
        System.Threading.Tasks.Task<TestePratico.Domain.Validation.ValidationResult> RemoveAsync(TestePratico.Domain.Entities.UF entity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAppServiceBaseOf_UFChannel : TestePratico.Web.WCF.UFAppService.IAppServiceBaseOf_UF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AppServiceBaseOf_UFClient : System.ServiceModel.ClientBase<TestePratico.Web.WCF.UFAppService.IAppServiceBaseOf_UF>, TestePratico.Web.WCF.UFAppService.IAppServiceBaseOf_UF {
        
        public AppServiceBaseOf_UFClient() {
        }
        
        public AppServiceBaseOf_UFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AppServiceBaseOf_UFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AppServiceBaseOf_UFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AppServiceBaseOf_UFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestePratico.Domain.Entities.UF GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public System.Threading.Tasks.Task<TestePratico.Domain.Entities.UF> GetByIdAsync(int id) {
            return base.Channel.GetByIdAsync(id);
        }
        
        public TestePratico.Domain.Entities.UF[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<TestePratico.Domain.Entities.UF[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public TestePratico.Domain.Validation.ValidationResult Add(TestePratico.Domain.Entities.UF entity) {
            return base.Channel.Add(entity);
        }
        
        public System.Threading.Tasks.Task<TestePratico.Domain.Validation.ValidationResult> AddAsync(TestePratico.Domain.Entities.UF entity) {
            return base.Channel.AddAsync(entity);
        }
        
        public TestePratico.Domain.Validation.ValidationResult Update(TestePratico.Domain.Entities.UF entity) {
            return base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task<TestePratico.Domain.Validation.ValidationResult> UpdateAsync(TestePratico.Domain.Entities.UF entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public TestePratico.Domain.Validation.ValidationResult Remove(TestePratico.Domain.Entities.UF entity) {
            return base.Channel.Remove(entity);
        }
        
        public System.Threading.Tasks.Task<TestePratico.Domain.Validation.ValidationResult> RemoveAsync(TestePratico.Domain.Entities.UF entity) {
            return base.Channel.RemoveAsync(entity);
        }
    }
}
