//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestePratico.Web.WCF.PessoaAppService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF.PessoaAppService.IAppServiceBaseOf_Pessoa")]
    public interface IAppServiceBaseOf_Pessoa {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppServiceBaseOf_Pessoa/GetById", ReplyAction="http://tempuri.org/IAppServiceBaseOf_Pessoa/GetByIdResponse")]
        TestePratico.Domain.Entities.Pessoa GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppServiceBaseOf_Pessoa/GetById", ReplyAction="http://tempuri.org/IAppServiceBaseOf_Pessoa/GetByIdResponse")]
        System.Threading.Tasks.Task<TestePratico.Domain.Entities.Pessoa> GetByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppServiceBaseOf_Pessoa/GetAll", ReplyAction="http://tempuri.org/IAppServiceBaseOf_Pessoa/GetAllResponse")]
        TestePratico.Domain.Entities.Pessoa[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppServiceBaseOf_Pessoa/GetAll", ReplyAction="http://tempuri.org/IAppServiceBaseOf_Pessoa/GetAllResponse")]
        System.Threading.Tasks.Task<TestePratico.Domain.Entities.Pessoa[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppServiceBaseOf_Pessoa/Add", ReplyAction="http://tempuri.org/IAppServiceBaseOf_Pessoa/AddResponse")]
        TestePratico.Domain.Validation.ValidationResult Add(TestePratico.Domain.Entities.Pessoa entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppServiceBaseOf_Pessoa/Add", ReplyAction="http://tempuri.org/IAppServiceBaseOf_Pessoa/AddResponse")]
        System.Threading.Tasks.Task<TestePratico.Domain.Validation.ValidationResult> AddAsync(TestePratico.Domain.Entities.Pessoa entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppServiceBaseOf_Pessoa/Update", ReplyAction="http://tempuri.org/IAppServiceBaseOf_Pessoa/UpdateResponse")]
        TestePratico.Domain.Validation.ValidationResult Update(TestePratico.Domain.Entities.Pessoa entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppServiceBaseOf_Pessoa/Update", ReplyAction="http://tempuri.org/IAppServiceBaseOf_Pessoa/UpdateResponse")]
        System.Threading.Tasks.Task<TestePratico.Domain.Validation.ValidationResult> UpdateAsync(TestePratico.Domain.Entities.Pessoa entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppServiceBaseOf_Pessoa/Remove", ReplyAction="http://tempuri.org/IAppServiceBaseOf_Pessoa/RemoveResponse")]
        TestePratico.Domain.Validation.ValidationResult Remove(TestePratico.Domain.Entities.Pessoa entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppServiceBaseOf_Pessoa/Remove", ReplyAction="http://tempuri.org/IAppServiceBaseOf_Pessoa/RemoveResponse")]
        System.Threading.Tasks.Task<TestePratico.Domain.Validation.ValidationResult> RemoveAsync(TestePratico.Domain.Entities.Pessoa entity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAppServiceBaseOf_PessoaChannel : TestePratico.Web.WCF.PessoaAppService.IAppServiceBaseOf_Pessoa, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AppServiceBaseOf_PessoaClient : System.ServiceModel.ClientBase<TestePratico.Web.WCF.PessoaAppService.IAppServiceBaseOf_Pessoa>, TestePratico.Web.WCF.PessoaAppService.IAppServiceBaseOf_Pessoa {
        
        public AppServiceBaseOf_PessoaClient() {
        }
        
        public AppServiceBaseOf_PessoaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AppServiceBaseOf_PessoaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AppServiceBaseOf_PessoaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AppServiceBaseOf_PessoaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestePratico.Domain.Entities.Pessoa GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public System.Threading.Tasks.Task<TestePratico.Domain.Entities.Pessoa> GetByIdAsync(int id) {
            return base.Channel.GetByIdAsync(id);
        }
        
        public TestePratico.Domain.Entities.Pessoa[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<TestePratico.Domain.Entities.Pessoa[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public TestePratico.Domain.Validation.ValidationResult Add(TestePratico.Domain.Entities.Pessoa entity) {
            return base.Channel.Add(entity);
        }
        
        public System.Threading.Tasks.Task<TestePratico.Domain.Validation.ValidationResult> AddAsync(TestePratico.Domain.Entities.Pessoa entity) {
            return base.Channel.AddAsync(entity);
        }
        
        public TestePratico.Domain.Validation.ValidationResult Update(TestePratico.Domain.Entities.Pessoa entity) {
            return base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task<TestePratico.Domain.Validation.ValidationResult> UpdateAsync(TestePratico.Domain.Entities.Pessoa entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public TestePratico.Domain.Validation.ValidationResult Remove(TestePratico.Domain.Entities.Pessoa entity) {
            return base.Channel.Remove(entity);
        }
        
        public System.Threading.Tasks.Task<TestePratico.Domain.Validation.ValidationResult> RemoveAsync(TestePratico.Domain.Entities.Pessoa entity) {
            return base.Channel.RemoveAsync(entity);
        }
    }
}
